# Generated by Django 4.1.7 on 2023-04-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_bank_branch_bank_name_alter_bank_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bank_name',
            new_name='bank_id',
        ),
    ]
